config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  devise_for :users

  resources :cocktails, only: :index do
    member do
      post 'toggle_favorite', to: "cocktails#toggle_favorite"
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  acts_as_favoritable
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  extend ActsAsFavoritor::FavoriteScopes

  belongs_to :favoritable, polymorphic: true
  belongs_to :favoritor, polymorphic: true

  def block!
    update!(blocked: true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable

  acts_as_favoritor
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :authenticate_user!
  def index
    @cocktails = Cocktail.all
    @favorite_cocktails = current_user.favorited_by_type('Cocktail')
  end

  def toggle_favorite
    @cocktail = Cocktail.find(params[:id])
    current_user.favorited?(@cocktail) ? current_user.unfavorite(@cocktail) : current_user.favorite(@cocktail)
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/cocktails/_cocktail.html.erb
<div class="favorite" data-id="<%= cocktail.id %>">
  <h3><%= cocktail.name %></h3>
  <p><%= cocktail.preparation %></p>
</div>

app/views/cocktails/_like_button.html.erb
<div class="like-icon mx-2 <%= 'red' if current_user.favorited?(cocktail) %>" data-id="<%= cocktail.id %>">
  <i class="fas fa-heart"></i>
</div>

app/views/cocktails/index.html.erb
<div class="container">
  <h1>Cocktails</h1>
  <hr>
  <div class="row">
    <div class="col-xs-12 col-sm-6">
      <% @cocktails.each do |cocktail| %>
        <div class="d-flex">
          <div>
            <%= link_to toggle_favorite_cocktail_path(cocktail), remote: true, method: :post do %>
              <%= render 'cocktails/like_button', cocktail: cocktail %>
            <% end %>
          </div>
          <div>
            <h3><%= cocktail.name %></h3>
            <p><%= cocktail.preparation %></p>
          </div>
        </div>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-6">
      <h3>Liked Cocktails</h3>
      <div class="favorites">
        <% @favorite_cocktails.each do |cocktail| %>
          <%= render 'cocktail', cocktail: cocktail %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cocktails/toggle_favorite.js.erb
var cocktailId = '<%= @cocktail.id%>'



function toggleLikeButton(cocktailId, favoritedCocktail) {
  let likeButton = document.querySelector(`.like-icon[data-id='${cocktailId}']`)
  likeButton.classList.toggle('red');
  if (likeButton.classList.contains('red')) {
    const favoriteList = document.querySelector('.favorites');
    favoriteList.insertAdjacentHTML('beforeend', favoritedCocktail)
  }
  else {
    document.querySelector(`.favorite[data-id='${cocktailId}']`).remove()
  }
}

toggleLikeButton(cocktailId, '<%= j render "cocktails/cocktail", cocktail: @cocktail %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LikeDislikeDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<!-- As a link -->
<nav class="navbar navbar-light bg-light">
  <%= link_to "Liking/Disliking Demo", root_path, class: "navbar-brand"  %>
  <% if user_signed_in? %>
    <%= link_to "Logout", destroy_user_session_path, method: :delete  %>
  <% else %>
    <%= link_to "Login", new_user_session_path %>
  <% end %>
</nav>